#  Code Book

This code book summarizes the resulting data fields in tidy_data.txt.

## Identifiers

Subject - The ID of the test subject
Activity - The type of activity performed when the corresponding measurements were taken

## Measurements

timeDomainBodyAccelerometerMeanX
timeDomainBodyAccelerometerMeanY
timeDomainBodyAccelerometerMeanZ
timeDomainBodyAccelerometerSTDX
timeDomainBodyAccelerometerSTDY
timeDomainBodyAccelerometerSTDZ
timeDomainGravityAccelerometerMeanX
timeDomainGravityAccelerometerMeanY
timeDomainGravityAccelerometerMeanZ
timeDomainGravityAccelerometerSTDX
timeDomainGravityAccelerometerSTDY
timeDomainGravityAccelerometerSTDZ
timeDomainBodyAccelerometerJerkMeanX
timeDomainBodyAccelerometerJerkMeanY
timeDomainBodyAccelerometerJerkMeanZ
timeDomainBodyAccelerometerJerkSTDX
timeDomainBodyAccelerometerJerkSTDY
timeDomainBodyAccelerometerJerkSTDZ
timeDomainBodyGyroscopeMeanX
timeDomainBodyGyroscopeMeanY
timeDomainBodyGyroscopeMeanZ
timeDomainBodyGyroscopeSTDX
timeDomainBodyGyroscopeSTDY
timeDomainBodyGyroscopeSTDZ
timeDomainBodyGyroscopeJerkMeanX
timeDomainBodyGyroscopeJerkMeanY
timeDomainBodyGyroscopeJerkMeanZ
timeDomainBodyGyroscopeJerkSTDX
timeDomainBodyGyroscopeJerkSTDY
timeDomainBodyGyroscopeJerkSTDZ
timeDomainBodyAccelerometerMagnitudeMean
timeDomainBodyAccelerometerMagnitudeSTD
timeDomainGravityAccelerometerMagnitudeMean
timeDomainGravityAccelerometerMagnitudeSTD
timeDomainBodyAccelerometerJerkMagnitudeMean
timeDomainBodyAccelerometerJerkMagnitudeSTD
timeDomainBodyGyroscopeMagnitudeMean
timeDomainBodyGyroscopeMagnitudeSTD
timeDomainBodyGyroscopeJerkMagnitudeMean
timeDomainBodyGyroscopeJerkMagnitudeSTD
frequencyDomainBodyAccelerometerMeanX
frequencyDomainBodyAccelerometerMeanY
frequencyDomainBodyAccelerometerMeanZ
frequencyDomainBodyAccelerometerSTDX
frequencyDomainBodyAccelerometerSTDY
frequencyDomainBodyAccelerometerSTDZ
frequencyDomainBodyAccelerometerMeanFrequencyX
frequencyDomainBodyAccelerometerMeanFrequencyY
frequencyDomainBodyAccelerometerMeanFrequencyZ
frequencyDomainBodyAccelerometerJerkMeanX
frequencyDomainBodyAccelerometerJerkMeanY
frequencyDomainBodyAccelerometerJerkMeanZ
frequencyDomainBodyAccelerometerJerkSTDX
frequencyDomainBodyAccelerometerJerkSTDY
frequencyDomainBodyAccelerometerJerkSTDZ
frequencyDomainBodyAccelerometerJerkMeanFrequencyX
frequencyDomainBodyAccelerometerJerkMeanFrequencyY
frequencyDomainBodyAccelerometerJerkMeanFrequencyZ
frequencyDomainBodyGyroscopeMeanX
frequencyDomainBodyGyroscopeMeanY
frequencyDomainBodyGyroscopeMeanZ
frequencyDomainBodyGyroscopeSTDX
frequencyDomainBodyGyroscopeSTDY
frequencyDomainBodyGyroscopeSTDZ
frequencyDomainBodyGyroscopeMeanFrequencyX
frequencyDomainBodyGyroscopeMeanFrequencyY
frequencyDomainBodyGyroscopeMeanFrequencyZ
frequencyDomainBodyAccelerometerMagnitudeMean
frequencyDomainBodyAccelerometerMagnitudeSTD
frequencyDomainBodyAccelerometerMagnitudeMeanFrequency
frequencyDomainBodyAccelerometerJerkMagnitudeMean
frequencyDomainBodyAccelerometerJerkMagnitudeSTD
frequencyDomainBodyAccelerometerJerkMagnitudeMeanFrequency
frequencyDomainBodyGyroscopeMagnitudeMean
frequencyDomainBodyGyroscopeMagnitudeSTD
frequencyDomainBodyGyroscopeMagnitudeMeanFrequency
frequencyDomainBodyGyroscopeJerkMagnitudeMean
frequencyDomainBodyGyroscopeJerkMagnitudeSTD
frequencyDomainBodyGyroscopeJerkMagnitudeMeanFrequency

## Activity Labels

* WALKING (value 1): subject was walking during the test
* WALKING_UPSTAIRS (value 2): subject was walking up a staircase during the test
* WALKING_DOWNSTAIRS (value 3): subject was walking down a staircase during the test
* SITTING (value 4): subject was sitting during the test
* STANDING (value 5): subject was standing during the test
* LAYING (value 6): subject was laying down during the test
